### ISSUE TITLE
Max Payne 3 incompatibility

### ISSUE THREAD

**Issue by deton24** [VolsandJezuz/Rinput-Library#4]
Used this version:
https://fearless-assassins.com/files/file/1656-rinput/

Game won't even start with Rinput.

**Comment by VolsandJezuz** [comment]
Probably because of the injector or the hooking method. Would require too much time for me to investigate implementing a fix into the existing code, but in the future I may rework RInput and the injector from the ground up, and that would probably make it compatible with MP1-3. But that wouldn't be part of this repository, so I'm going to close the MP-related issues. Thanks for your feedback and sorry for the delayed response.
